name: Flutter Web PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href="/flutter_namer/pr-preview/pr-${{ github.event.number }}"/


      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/web
          preview-branch: main
